// This file was generated by prisma-field-encryption.

import type { PrismaClient } from '../C:\Users\master\Desktop\appFisio-\backend\node_modules\@prisma\client'
import { migrate as migratePatientProfile } from './PatientProfile'

export interface ProgressReport {
  model: string
  processed: number
  totalCount: number
  performance: number
}

export type ProgressReportCallback = (
  progress: ProgressReport
) => void | Promise<void>

export const defaultProgressReport: ProgressReportCallback = ({
  model,
  totalCount,
  processed,
  performance
}) => {
  const length = totalCount.toString().length
  const pct = Math.round((100 * processed) / totalCount)
    .toString()
    .padStart(3)
  console.info(
    `${model.padEnd(14)} ${pct}% processed ${processed
      .toString()
      .padStart(length)} / ${totalCount} (took ${performance.toFixed(2)}ms)`
  )
}

// --

export type MigrationReport = {
  PatientProfile: number
}

/**
 * Migrate models sequentially.
 *
 * Processed models:
 * - PatientProfile
 *
 * @returns a dictionary of the number of processed records per model.
 */
export async function migrate(
  client: PrismaClient,
  reportProgress: ProgressReportCallback = defaultProgressReport
): Promise<MigrationReport> {
  const processedPatientProfile = await migratePatientProfile(client, reportProgress)
  return {
    PatientProfile: processedPatientProfile
  }
}
