// This file was generated by prisma-field-encryption.

import type { PrismaClient, PatientProfile } from '../C:\Users\master\Desktop\appFisio-\backend\node_modules\@prisma\client'
import {
  ProgressReportCallback,
  defaultProgressReport,
  visitRecords
} from 'prisma-field-encryption/dist/generator/runtime'

type Cursor = PatientProfile['id']

export async function migrate(
  client: PrismaClient,
  reportProgress: ProgressReportCallback = defaultProgressReport
): Promise<number> {
  return visitRecords<PrismaClient, Cursor>({
    modelName: 'PatientProfile',
    client,
    getTotalCount: client.patientProfile.count,
    migrateRecord,
    reportProgress,
  })
}

async function migrateRecord(client: PrismaClient, cursor: Cursor | undefined) {
  return await client.$transaction(async tx => {
    const record = await tx.patientProfile.findFirst({
      take: 1,
      skip: cursor === undefined ? undefined : 1,
      ...(cursor === undefined
        ? {}
        : {
            cursor: {
              id: cursor
            }
          }),
      orderBy: {
        id: 'asc'
      },
      select: {
        id: true,
        telefone: true,
        estado: true,
        cidade: true,
        bairro: true,
        endereco: true,
        cep: true,
        notes: true
      }
    })
    if (!record) {
      return cursor
    }
    await tx.patientProfile.update({
      where: {
        id: record.id
      },
      data: {
        telefone: record.telefone,
        estado: record.estado,
        cidade: record.cidade,
        bairro: record.bairro,
        endereco: record.endereco,
        cep: record.cep,
        notes: record.notes
      }
    })
    return record.id
  })
}

/**
 * Internal model:
 * {
 *   "cursor": "id",
 *   "fields": {
 *     "telefone": {
 *       "encrypt": true,
 *       "strictDecryption": false
 *     },
 *     "estado": {
 *       "encrypt": true,
 *       "strictDecryption": false
 *     },
 *     "cidade": {
 *       "encrypt": true,
 *       "strictDecryption": false
 *     },
 *     "bairro": {
 *       "encrypt": true,
 *       "strictDecryption": false
 *     },
 *     "endereco": {
 *       "encrypt": true,
 *       "strictDecryption": false
 *     },
 *     "cep": {
 *       "encrypt": true,
 *       "strictDecryption": false
 *     },
 *     "notes": {
 *       "encrypt": true,
 *       "strictDecryption": false
 *     }
 *   },
 *   "connections": {
 *     "user": {
 *       "modelName": "User",
 *       "isList": false
 *     }
 *   }
 * }
 */
