// This file was generated by prisma-field-encryption.

import type { PrismaClient, User } from '../C:\Users\master\Desktop\appFisio-\backend\node_modules\@prisma\client'
import {
  ProgressReportCallback,
  defaultProgressReport,
  visitRecords
} from 'prisma-field-encryption/dist/generator/runtime'

type Cursor = User['id']

export async function migrate(
  client: PrismaClient,
  reportProgress: ProgressReportCallback = defaultProgressReport
): Promise<number> {
  return visitRecords<PrismaClient, Cursor>({
    modelName: 'User',
    client,
    getTotalCount: client.user.count,
    migrateRecord,
    reportProgress,
  })
}

async function migrateRecord(client: PrismaClient, cursor: Cursor | undefined) {
  return await client.$transaction(async tx => {
    const record = await tx.user.findFirst({
      take: 1,
      skip: cursor === undefined ? undefined : 1,
      ...(cursor === undefined
        ? {}
        : {
            cursor: {
              id: cursor
            }
          }),
      orderBy: {
        id: 'asc'
      },
      select: {
        id: true,
        telefone: true
      }
    })
    if (!record) {
      return cursor
    }
    await tx.user.update({
      where: {
        id: record.id
      },
      data: {
        telefone: record.telefone
      }
    })
    return record.id
  })
}

/**
 * Internal model:
 * {
 *   "cursor": "id",
 *   "fields": {
 *     "telefone": {
 *       "encrypt": true,
 *       "strictDecryption": false
 *     }
 *   },
 *   "connections": {
 *     "achievements": {
 *       "modelName": "Achievement",
 *       "isList": true
 *     },
 *     "patientProfile": {
 *       "modelName": "PatientProfile",
 *       "isList": false
 *     },
 *     "prescriptions": {
 *       "modelName": "Prescription",
 *       "isList": true
 *     }
 *   }
 * }
 */
